// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Libreria_API.Models;

public partial class LibreriaContext : DbContext
{
    public LibreriaContext(DbContextOptions<LibreriaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Autore> Autores { get; set; }

    public virtual DbSet<EstadoPedido> EstadosPedidos { get; set; }

    public virtual DbSet<AutoresLibro> AutoresLibros { get; set; }

    public virtual DbSet<Barrio> Barrios { get; set; }

    public virtual DbSet<Categoria> Categorias { get; set; }

    public virtual DbSet<Ciudade> Ciudades { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Contacto> Contactos { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }

    public virtual DbSet<DetallePedido> DetallePedidos { get; set; }

    public virtual DbSet<Editoriale> Editoriales { get; set; }

    public virtual DbSet<EstadosEnvio> EstadosEnvios { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FacturasFormaspago> FacturasFormaspagos { get; set; }

    public virtual DbSet<Financiera> Financieras { get; set; }

    public virtual DbSet<FormapagosCliente> FormapagosClientes { get; set; }

    public virtual DbSet<FormasEnvio> FormasEnvios { get; set; }

    public virtual DbSet<FormasPago> FormasPagos { get; set; }

    public virtual DbSet<Genero> Generos { get; set; }

    public virtual DbSet<Idioma> Idiomas { get; set; }

    public virtual DbSet<Libro> Libros { get; set; }

    public virtual DbSet<LibrosCategoria> LibrosCategorias { get; set; }

    public virtual DbSet<LibrosGenero> LibrosGeneros { get; set; }

    public virtual DbSet<Nacionalidade> Nacionalidades { get; set; }

    public virtual DbSet<Pedido> Pedidos { get; set; }

    public virtual DbSet<Provincia> Provincias { get; set; }

    public virtual DbSet<Sexo> Sexos { get; set; }

    public virtual DbSet<TiposContacto> TiposContactos { get; set; }

    public virtual DbSet<TiposDocumento> TiposDocumentos { get; set; }

    public virtual DbSet<TrackingEnvio> TrackingEnvios { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autore>(entity =>
        {
            entity.HasKey(e => e.IdAutor).HasName("PK__autores__5FC3872DCA7C31ED");

            entity.ToTable("autores");

            entity.Property(e => e.IdAutor).HasColumnName("id_autor");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Biografia)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("biografia");
            entity.Property(e => e.FechaNacimiento).HasColumnName("fecha_nacimiento");
            entity.Property(e => e.IdNacionalidad).HasColumnName("id_nacionalidad");
            entity.Property(e => e.IdSexo).HasColumnName("id_sexo");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");

            entity.HasOne(d => d.IdNacionalidadNavigation).WithMany(p => p.Autores)
                .HasForeignKey(d => d.IdNacionalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__autores__id_naci__114A936A");

            entity.HasOne(d => d.IdSexoNavigation).WithMany(p => p.Autores)
                .HasForeignKey(d => d.IdSexo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__autores__id_sexo__123EB7A3");
        });

        modelBuilder.Entity<EstadoPedido>(entity =>
        {
        entity.HasKey(e => e.IdEstadoPedido)
            .HasName("PK__Estados_Pedido");

        entity.ToTable("Estados_Pedido");

        entity.Property(e => e.IdEstadoPedido)
            .HasColumnName("IdEstadoPedido");

        entity.Property(e => e.Nombre)
            .IsRequired()
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("Nombre");

        entity.HasMany(e => e.Pedidos)
            .WithOne(p => p.EstadoPedido)
            .HasForeignKey(p => p.IdEstadoPedido)
            .HasConstraintName("FK_pedidos_estados_pedido");
        });



        modelBuilder.Entity<AutoresLibro>(entity =>
        {
            entity.HasKey(e => e.IdAutorLibro).HasName("PK__autores___5CDCA301FCAC3152");

            entity.ToTable("autores_libros");

            entity.Property(e => e.IdAutorLibro).HasColumnName("id_autor_libro");
            entity.Property(e => e.IdAutor).HasColumnName("id_autor");
            entity.Property(e => e.IdLibro).HasColumnName("id_libro");

            entity.HasOne(d => d.IdAutorNavigation).WithMany(p => p.AutoresLibros)
                .HasForeignKey(d => d.IdAutor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__autores_l__id_au__1332DBDC");

            entity.HasOne(d => d.IdLibroNavigation).WithMany(p => p.AutoresLibros)
                .HasForeignKey(d => d.IdLibro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__autores_l__id_li__14270015");
        });

        modelBuilder.Entity<Barrio>(entity =>
        {
            entity.HasKey(e => e.IdBarrio).HasName("PK__barrios__1121F0B2C57F10B5");

            entity.ToTable("barrios");

            entity.Property(e => e.IdBarrio).HasColumnName("id_barrio");
            entity.Property(e => e.Barrio1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("barrio");
            entity.Property(e => e.IdCiudad).HasColumnName("id_ciudad");

            entity.HasOne(d => d.IdCiudadNavigation).WithMany(p => p.Barrios)
                .HasForeignKey(d => d.IdCiudad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__barrios__id_ciud__07C12930");
        });

        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.HasKey(e => e.IdCategoria).HasName("PK__categori__CD54BC5AD0CE5A28");

            entity.ToTable("categorias");

            entity.Property(e => e.IdCategoria).HasColumnName("id_categoria");
            entity.Property(e => e.Categoria1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("categoria");
        });

        modelBuilder.Entity<Ciudade>(entity =>
        {
            entity.HasKey(e => e.IdCiudad).HasName("PK__ciudades__B7DC4CD558AB4DFB");

            entity.ToTable("ciudades");

            entity.Property(e => e.IdCiudad).HasColumnName("id_ciudad");
            entity.Property(e => e.Ciudad)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ciudad");
            entity.Property(e => e.IdProvincia).HasColumnName("id_provincia");

            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.Ciudades)
                .HasForeignKey(d => d.IdProvincia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ciudades__id_pro__06CD04F7");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.CodCliente).HasName("PK__clientes__08ED61F3DBF4000C");

            entity.ToTable("clientes");

            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.Calle)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("calle");
            entity.Property(e => e.Cp)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("cp");
            entity.Property(e => e.Dpto)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("dpto");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.FechaNacimiento).HasColumnName("fecha_nacimiento");
            entity.Property(e => e.FechaRegistro)
                .HasColumnType("datetime")
                .HasColumnName("fecha_registro");
            entity.Property(e => e.IdBarrio).HasColumnName("id_barrio");
            entity.Property(e => e.IdNacionalidad).HasColumnName("id_nacionalidad");
            entity.Property(e => e.IdSexo).HasColumnName("id_sexo");
            entity.Property(e => e.IdTipoDoc).HasColumnName("id_tipo_doc");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.Nro).HasColumnName("nro");
            entity.Property(e => e.NroDoc).HasColumnName("nro_doc");
            entity.Property(e => e.Piso)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("piso");

            entity.HasOne(d => d.IdBarrioNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdBarrio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__clientes__id_bar__08B54D69");

            entity.HasOne(d => d.IdNacionalidadNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdNacionalidad)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__clientes__id_nac__0A9D95DB");

            entity.HasOne(d => d.IdSexoNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdSexo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__clientes__id_sex__09A971A2");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdTipoDoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__clientes__id_tip__0B91BA14");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("FK__clientes__IdUsua__0C85DE4D");
        });

        modelBuilder.Entity<Contacto>(entity =>
        {
            entity.HasKey(e => e.IdContacto).HasName("PK__contacto__099A52B89843334C");

            entity.ToTable("contactos");

            entity.Property(e => e.IdContacto).HasColumnName("id_contacto");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Contacto1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("contacto");
            entity.Property(e => e.IdTipoContacto).HasColumnName("id_tipo_contacto");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__contactos__cod_c__0D7A0286");

            entity.HasOne(d => d.IdTipoContactoNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.IdTipoContacto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__contactos__id_ti__0E6E26BF");
        });

        modelBuilder.Entity<DetalleFactura>(entity =>
        {
            entity.HasKey(e => e.IdDetalleFactura).HasName("PK__detalle___F6BFE3437EE650FB");

            entity.ToTable("detalle_facturas");

            entity.Property(e => e.IdDetalleFactura).HasColumnName("id_detalle_factura");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CodLibro).HasColumnName("cod_libro");
            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
            entity.Property(e => e.Recargo)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("recargo");

            entity.HasOne(d => d.CodLibroNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.CodLibro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_f__cod_l__208CD6FA");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_f__nro_f__1F98B2C1");
        });

        modelBuilder.Entity<DetallePedido>(entity =>
        {
            entity.HasKey(e => e.IdDetallePedido).HasName("PK__detalle___C08768CFBB739C82");

            entity.ToTable("detalle_pedidos");

            entity.Property(e => e.IdDetallePedido).HasColumnName("id_detalle_pedido");
            entity.Property(e => e.Cantidad).HasColumnName("cantidad");
            entity.Property(e => e.CodLibro).HasColumnName("cod_libro");
            entity.Property(e => e.NroPedido).HasColumnName("nro_pedido");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");

            entity.HasOne(d => d.CodLibroNavigation).WithMany(p => p.DetallePedidos)
                .HasForeignKey(d => d.CodLibro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_p__cod_l__1BC821DD");

            entity.HasOne(d => d.NroPedidoNavigation).WithMany(p => p.DetallePedidos)
                .HasForeignKey(d => d.NroPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_p__nro_p__1CBC4616");
        });

        modelBuilder.Entity<Editoriale>(entity =>
        {
            entity.HasKey(e => e.IdEditorial).HasName("PK__editoria__10C1DD0207266A1D");

            entity.ToTable("editoriales");

            entity.Property(e => e.IdEditorial).HasColumnName("id_editorial");
            entity.Property(e => e.Editorial)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("editorial");
        });

        modelBuilder.Entity<EstadosEnvio>(entity =>
        {
            entity.HasKey(e => e.IdEstadoEnvio).HasName("PK__estados___5AAF6D3A433337FC");

            entity.ToTable("estados_envios");

            entity.Property(e => e.IdEstadoEnvio).HasColumnName("id_estado_envio");
            entity.Property(e => e.EstadoActual)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estado_actual");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.NroFactura).HasName("PK__facturas__B31FA9AFA6F31375");

            entity.ToTable("facturas");

            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.CostoEnvio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("costo_envio");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.FechaEntrega)
                .HasColumnType("datetime")
                .HasColumnName("fecha_entrega");
            entity.Property(e => e.FechaPago)
                .HasColumnType("datetime")
                .HasColumnName("fecha_pago");
            entity.Property(e => e.IdFormaEnvio).HasColumnName("id_forma_envio");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__facturas__cod_cl__1DB06A4F");

            entity.HasOne(d => d.IdFormaEnvioNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdFormaEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__facturas__id_for__1EA48E88");
        });

        modelBuilder.Entity<FacturasFormaspago>(entity =>
        {
            entity.HasKey(e => e.IdFacturaPago).HasName("PK__facturas__D7CA32CA3FFD3E4A");

            entity.ToTable("facturas_formaspago");

            entity.Property(e => e.IdFacturaPago).HasColumnName("id_factura_pago");
            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");
            entity.Property(e => e.MontoParcial)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("monto_parcial");
            entity.Property(e => e.NroFactura).HasColumnName("nro_factura");

            entity.HasOne(d => d.IdFormaPagoNavigation).WithMany(p => p.FacturasFormaspagos)
                .HasForeignKey(d => d.IdFormaPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__facturas___id_fo__22751F6C");

            entity.HasOne(d => d.NroFacturaNavigation).WithMany(p => p.FacturasFormaspagos)
                .HasForeignKey(d => d.NroFactura)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__facturas___nro_f__2180FB33");
        });

        modelBuilder.Entity<Financiera>(entity =>
        {
            entity.HasKey(e => e.IdFinanciera).HasName("PK__financie__B6AE05DA493BDED7");

            entity.ToTable("financieras");

            entity.Property(e => e.IdFinanciera).HasColumnName("id_financiera");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<FormapagosCliente>(entity =>
        {
            entity.HasKey(e => e.IdFormapagoCliente).HasName("PK__formapag__781EDA7F0E02EAB6");

            entity.ToTable("formapagos_clientes");

            entity.Property(e => e.IdFormapagoCliente).HasColumnName("id_formapago_cliente");
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Cvv).HasColumnName("cvv");
            entity.Property(e => e.FechaVencimiento).HasColumnName("fecha_vencimiento");
            entity.Property(e => e.IdFinanciera).HasColumnName("id_financiera");
            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");
            entity.Property(e => e.NumTarjeta).HasColumnName("num_tarjeta");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.FormapagosClientes)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__formapago__cod_c__236943A5");

            entity.HasOne(d => d.IdFinancieraNavigation).WithMany(p => p.FormapagosClientes)
                .HasForeignKey(d => d.IdFinanciera)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__formapago__id_fi__25518C17");

            entity.HasOne(d => d.IdFormaPagoNavigation).WithMany(p => p.FormapagosClientes)
                .HasForeignKey(d => d.IdFormaPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__formapago__id_fo__245D67DE");
        });

        modelBuilder.Entity<FormasEnvio>(entity =>
        {
            entity.HasKey(e => e.IdFormaEnvio).HasName("PK__formas_e__FB2C7E215765FE0D");

            entity.ToTable("formas_envios");

            entity.Property(e => e.IdFormaEnvio).HasColumnName("id_forma_envio");
            entity.Property(e => e.FormaEnvio)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("forma_envio");
        });

        modelBuilder.Entity<FormasPago>(entity =>
        {
            entity.HasKey(e => e.IdFormaPago).HasName("PK__formas_p__DA9B39EEF3278C03");

            entity.ToTable("formas_pagos");

            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");
            entity.Property(e => e.FormaPago)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("forma_pago");
        });

        modelBuilder.Entity<Genero>(entity =>
        {
            entity.HasKey(e => e.IdGenero).HasName("PK__generos__99A8E4F983610538");

            entity.ToTable("generos");

            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.Genero1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("genero");
        });

        modelBuilder.Entity<Idioma>(entity =>
        {
            entity.HasKey(e => e.IdIdioma).HasName("PK__idiomas__0BA1525F4F3019CC");

            entity.ToTable("idiomas");

            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");
            entity.Property(e => e.Idioma1)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("idioma");
        });

        modelBuilder.Entity<Libro>(entity =>
        {
            entity.HasKey(e => e.CodLibro).HasName("PK__libros__6BF7918E48637779");

            entity.ToTable("libros");

            entity.Property(e => e.CodLibro).HasColumnName("cod_libro");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.FechaLanzamiento).HasColumnName("fecha_lanzamiento");
            entity.Property(e => e.IdEditorial).HasColumnName("id_editorial");
            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");
            entity.Property(e => e.Isbn)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("isbn");
            entity.Property(e => e.Precio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("precio");
            entity.Property(e => e.Stock).HasColumnName("stock");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("titulo");

            entity.HasOne(d => d.IdEditorialNavigation).WithMany(p => p.Libros)
                .HasForeignKey(d => d.IdEditorial)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__libros__id_edito__0F624AF8");

            entity.HasOne(d => d.IdIdiomaNavigation).WithMany(p => p.Libros)
                .HasForeignKey(d => d.IdIdioma)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__libros__id_idiom__10566F31");
        });

        modelBuilder.Entity<LibrosCategoria>(entity =>
        {
            entity.HasKey(e => e.IdLibroCategoria).HasName("PK__libros_c__EDB5CF8C3987938B");

            entity.ToTable("libros_categorias");

            entity.Property(e => e.IdLibroCategoria).HasColumnName("id_libro_categoria");
            entity.Property(e => e.IdCategoria).HasColumnName("id_categoria");
            entity.Property(e => e.IdLibro).HasColumnName("id_libro");

            entity.HasOne(d => d.IdCategoriaNavigation).WithMany(p => p.LibrosCategoria)
                .HasForeignKey(d => d.IdCategoria)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__libros_ca__id_ca__17036CC0");

            entity.HasOne(d => d.IdLibroNavigation).WithMany(p => p.LibrosCategoria)
                .HasForeignKey(d => d.IdLibro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__libros_ca__id_li__17F790F9");
        });

        modelBuilder.Entity<LibrosGenero>(entity =>
        {
            entity.HasKey(e => e.IdLibroGenero).HasName("PK__libros_g__270E9C32145F50FA");

            entity.ToTable("libros_generos");

            entity.Property(e => e.IdLibroGenero).HasColumnName("id_libro_genero");
            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.IdLibro).HasColumnName("id_libro");

            entity.HasOne(d => d.IdGeneroNavigation).WithMany(p => p.LibrosGeneros)
                .HasForeignKey(d => d.IdGenero)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__libros_ge__id_ge__151B244E");

            entity.HasOne(d => d.IdLibroNavigation).WithMany(p => p.LibrosGeneros)
                .HasForeignKey(d => d.IdLibro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__libros_ge__id_li__160F4887");
        });

        modelBuilder.Entity<Nacionalidade>(entity =>
        {
            entity.HasKey(e => e.IdNacionalidad).HasName("PK__nacional__EDAEE094F63ADF97");

            entity.ToTable("nacionalidades");

            entity.Property(e => e.IdNacionalidad).HasColumnName("id_nacionalidad");
            entity.Property(e => e.Nacionalidad)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nacionalidad");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasKey(e => e.NroPedido).HasName("PK__pedidos__493904066A432A0E");

            entity.ToTable("pedidos");

            entity.Property(e => e.NroPedido).HasColumnName("nro_pedido");
            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.CodCliente).HasColumnName("cod_cliente");
            entity.Property(e => e.Fecha)
                .HasColumnType("datetime")
                .HasColumnName("fecha");
            entity.Property(e => e.FechaEntrega).HasColumnName("fecha_entrega");
            entity.Property(e => e.IdFormaEnvio).HasColumnName("id_forma_envio");
            entity.Property(e => e.InstruccionesAdicionales)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("instrucciones_adicionales");

            entity.HasOne(d => d.CodClienteNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.CodCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__pedidos__cod_cli__18EBB532");

            entity.HasOne(d => d.IdFormaEnvioNavigation).WithMany(p => p.Pedidos)
                .HasForeignKey(d => d.IdFormaEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__pedidos__id_form__19DFD96B");
        });

        modelBuilder.Entity<Provincia>(entity =>
        {
            entity.HasKey(e => e.IdProvincia).HasName("PK__provinci__66C18BFD098BFE88");

            entity.ToTable("provincias");

            entity.Property(e => e.IdProvincia).HasColumnName("id_provincia");
            entity.Property(e => e.Provincia1)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("provincia");
        });

        modelBuilder.Entity<Sexo>(entity =>
        {
            entity.HasKey(e => e.IdSexo).HasName("PK__sexos__D692FEE6250B406A");

            entity.ToTable("sexos");

            entity.Property(e => e.IdSexo).HasColumnName("id_sexo");
            entity.Property(e => e.Sexo1)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("sexo");
        });

        modelBuilder.Entity<TiposContacto>(entity =>
        {
            entity.HasKey(e => e.IdTipoContacto).HasName("PK__tipos_co__CA854C0D7A5DBBAB");

            entity.ToTable("tipos_contactos");

            entity.Property(e => e.IdTipoContacto).HasColumnName("id_tipo_contacto");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<TiposDocumento>(entity =>
        {
            entity.HasKey(e => e.IdTipoDoc).HasName("PK__tipos_do__B0A524EAE1A1FC6A");

            entity.ToTable("tipos_documentos");

            entity.Property(e => e.IdTipoDoc).HasColumnName("id_tipo_doc");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo");
        });

        modelBuilder.Entity<TrackingEnvio>(entity =>
        {
            entity.HasKey(e => e.IdTracking).HasName("PK__tracking__8877058DAF6B9BFE");

            entity.ToTable("tracking_envios");

            entity.Property(e => e.IdTracking).HasColumnName("id_tracking");
            entity.Property(e => e.FechaEstado)
                .HasColumnType("datetime")
                .HasColumnName("fecha_estado");
            entity.Property(e => e.IdEstadoEnvio).HasColumnName("id_estado_envio");
            entity.Property(e => e.NroPedido).HasColumnName("nro_pedido");
            entity.Property(e => e.Observaciones)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("observaciones");

            entity.HasOne(d => d.IdEstadoEnvioNavigation).WithMany(p => p.TrackingEnvios)
                .HasForeignKey(d => d.IdEstadoEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tracking___id_es__2739D489");

            entity.HasOne(d => d.NroPedidoNavigation).WithMany(p => p.TrackingEnvios)
                .HasForeignKey(d => d.NroPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tracking___nro_p__2645B050");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuarios__5B65BF9784E6E51C");

            entity.HasIndex(e => e.NombreUsuario, "UQ__Usuarios__6B0F5AE05F9E8C88").IsUnique();

            entity.Property(e => e.ContrasenaHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FechaAlta)
                .HasDefaultValueSql("(sysdatetime())")
                .HasColumnType("datetime");
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Rol)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Cliente");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}